name: You get what you REPEAT
on: push
job:
    init:
        runs-on: self-hosted
        steps:
            - run: echo "Hello World, it's time to repeat this lab"
            - run: echo "Hostname is $($HOSTNAME)"